/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtTitle: typeof import('./src/components/artTitle/index.vue')['default']
    CsgoLightParticles: typeof import('./src/components/csgo/CsgoLightParticles.vue')['default']
    DiyLoading: typeof import('./src/components/DiyLoading/index.vue')['default']
    DiyLoading2: typeof import('./src/components/DiyLoading2/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ItemCardBox: typeof import('./src/components/ItemCardBox/index.vue')['default']
    Printer: typeof import('./src/components/printer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoybeanControlPanel: typeof import('./src/components/soybeanDemo/SoybeanControlPanel.vue')['default']
    SoybeanHero: typeof import('./src/components/soybeanDemo/SoybeanHero.vue')['default']
    SoybeanShowcase: typeof import('./src/components/soybeanDemo/SoybeanShowcase.vue')['default']
    UploadByNaviUI: typeof import('./src/components/uploadByNaviUI/index.vue')['default']
    WebBackgroundColorful: typeof import('./src/components/webBackgroundColorful/index.vue')['default']
  }
}
